@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Nov 29 00:43:17 +0700 2023
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim get_instruction_hex_behav -key {Behavioral:GET_INSTRUCTION:Functional:get_instruction_hex} -tclbatch get_instruction_hex.tcl -view L:/Projects/Dual_core_Microcontroller/get_instruction_hex_behav.wcfg -log simulate.log"
call xsim  get_instruction_hex_behav -key {Behavioral:GET_INSTRUCTION:Functional:get_instruction_hex} -tclbatch get_instruction_hex.tcl -view L:/Projects/Dual_core_Microcontroller/get_instruction_hex_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
